# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `enummify` gem.
# Please instead update this file by running `bin/tapioca gem enummify`.


# typed: strict
# frozen_string_literal: true

# pkg:gem/enummify#lib/enummify/enum.rb:4
module Enummify; end

# A typed set of immutable, named instances with string serialization.
#
# pkg:gem/enummify#lib/enummify/enum.rb:6
class Enummify::Enum
  extend T::Sig

  # pkg:gem/enummify#lib/enummify/enum.rb:101
  sig { params(serialized: T.nilable(::String)).void }
  def initialize(serialized = T.unsafe(nil)); end

  # Store only the serialized string so Marshal loading uses the registered member.
  #
  # pkg:gem/enummify#lib/enummify/enum.rb:58
  sig { params(_depth: ::Integer).returns(::String) }
  def _dump(_depth); end

  # Enum members are immutable singletons, including copies requested as unfrozen.
  #
  # pkg:gem/enummify#lib/enummify/enum.rb:65
  sig { params(freeze: T.nilable(T::Boolean)).returns(T.self_type) }
  def clone(freeze: T.unsafe(nil)); end

  # pkg:gem/enummify#lib/enummify/enum.rb:71
  sig { returns(T.self_type) }
  def dup; end

  # pkg:gem/enummify#lib/enummify/enum.rb:76
  sig { returns(::String) }
  def inspect; end

  # pkg:gem/enummify#lib/enummify/enum.rb:81
  sig { returns(::String) }
  def serialize; end

  # pkg:gem/enummify#lib/enummify/enum.rb:86
  sig { returns(::String) }
  def to_s; end

  private

  # The constant name is only available after construction has returned.
  #
  # pkg:gem/enummify#lib/enummify/enum.rb:94
  sig { params(constant: ::Symbol).returns(::String) }
  def finalize(constant); end

  class << self
    # Restore the canonical member when loading a Marshal stream.
    #
    # pkg:gem/enummify#lib/enummify/enum.rb:32
    def _load(*args, **_arg1, &blk); end

    # Look up a member by its exact serialized string.
    #
    # pkg:gem/enummify#lib/enummify/enum.rb:26
    sig { params(serialized: ::String).returns(T.attached_class) }
    def deserialize(serialized); end

    # Look up a member, returning nil for an unknown string.
    #
    # pkg:gem/enummify#lib/enummify/enum.rb:37
    sig { params(serialized: ::String).returns(T.nilable(T.attached_class)) }
    def try_deserialize(serialized); end

    # Return the members.
    #
    # pkg:gem/enummify#lib/enummify/enum.rb:43
    sig { returns(T::Array[T.attached_class]) }
    def values; end

    private

    # Register direct constants so only named members belong to the enum.
    #
    # pkg:gem/enummify#lib/enummify/enum.rb:12
    sig { params(constant: ::Symbol).void }
    def const_added(constant); end

    # Give each enum class its own registry.
    #
    # pkg:gem/enummify#lib/enummify/enum.rb:49
    sig { params(subclass: T.class_of(Enummify::Enum)).void }
    def inherited(subclass); end
  end
end

# pkg:gem/enummify#lib/enummify/version.rb:5
Enummify::VERSION = T.let(T.unsafe(nil), String)
