# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `optify-from_hash` gem.
# Please instead update this file by running `bin/tapioca gem optify-from_hash`.


# frozen_string_literal: true
# typed: strong

# pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:9
# Tools for working with configurations declared in files.
module Optify; end

# A base class for classes that can be created from a hash.
#
# pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:11
class Optify::FromHashable
  extend T::Sig
  extend T::Helpers

  abstract!

  # Compare this object with another object for equality.
  # @param other The object to compare.
  # @return [Boolean] true if the objects are equal; otherwise, false.
  #
  # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:169
  sig { params(other: T.untyped).returns(T::Boolean) }
  def ==(other); end

  # Support equality by value so that instances can be used in Sets and as Hash keys.
  #
  # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:180
  sig { params(other: T.untyped).returns(T::Boolean) }
  def eql?(other); end

  # @return [Integer] a hash value based on the object's class and instance variables.
  #
  # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:191
  sig { returns(::Integer) }
  def hash; end

  # Convert this object to a Hash recursively.
  # This is mostly the reverse operation of `from_hash`,
  # as keys will be symbols
  # and `from_hash` will convert strings to symbols if that's how the attribute is declared.
  # @return [Hash] The hash representation of this object.
  #
  # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:207
  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def to_h; end

  # Convert this object to a JSON string.
  #
  # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:197
  sig { params(state: T.nilable(::JSON::Ext::Generator::State)).returns(::String) }
  def to_json(state = T.unsafe(nil)); end

  class << self
    # Create a new immutable instance of the class from a hash.
    #
    # @param hash The hash to create the instance from.
    # @return The new instance.
    #
    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:56
    # Create a new instance of the class from a hash.
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T.attached_class) }
    def from_hash(hash); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:24
    sig { type_parameters(:T).params(subclass: T::Class[T.type_parameter(:T)]).void }
    def inherited(subclass); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:20
    sig { returns(T::Hash[::Symbol, ::T::Types::Base]) }
    def key_to_type; end

    private

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:37
    sig do
      type_parameters(:Type)
        .params(
          subclass: T::Class[T.type_parameter(:Type)]
        ).returns(T::Hash[::Symbol, ::T::Types::Base])
    end
    def _build_key_to_type(subclass); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:88
    sig do
      params(
        value: T::Array[T.untyped],
        unwrapped_type: T.untyped
      ).returns(T.any(T::Array[T.untyped], T::Set[T.untyped]))
    end
    def _convert_array(value, unwrapped_type); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:131
    sig { params(hash: T::Hash[T.untyped, T.untyped], type: ::T::Types::Base).returns(T.untyped) }
    def _convert_hash(hash, type); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:96
    sig { params(value: T.untyped, type: ::T::Types::Base).returns(T.untyped) }
    def _convert_value(value, type); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:221
    sig { params(value: T.untyped).returns(T.untyped) }
    def _convert_value_for_to_h(value); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:69
    sig { params(key: T.untyped).returns(::T::Types::Base) }
    def _get_value_type(key); end

    # pkg:gem/optify-from_hash#lib/optify_from_hash/from_hashable.rb:156
    sig { params(type: ::T::Types::Base).returns(::T::Types::Base) }
    def _unwrap_nilable(type); end
  end
end
