# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `require-hooks` gem.
# Please instead update this file by running `bin/tapioca gem require-hooks`.


# source://require-hooks//lib/require-hooks/api.rb#3
module RequireHooks
  class << self
    # Define a block to wrap the code loading.
    # The return value MUST be a result of calling the passed block.
    # For example, you can use such hooks for instrumentation, debugging purposes.
    #
    #    RequireHooks.around_load do |path, &block|
    #      puts "Loading #{path}"
    #      block.call.tap { puts "Loaded #{path}" }
    #    end
    #
    # source://require-hooks//lib/require-hooks/api.rb#103
    def around_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # source://require-hooks//lib/require-hooks/api.rb#139
    def context_for(path); end

    # source://require-hooks//lib/require-hooks/api.rb#168
    def contexts; end

    # This hook should be used to manually compile byte code to be loaded by the VM.
    # The arguments are (path, source = nil), where source is only defined if transformations took place.
    # Otherwise, you MUST read the source code from the file yourself.
    #
    # The return value MUST be either nil (continue to the next hook or default behavior) or a platform-specific bytecode object (e.g., RubyVM::InstructionSequence).
    #
    #   RequireHooks.hijack_load do |path, source|
    #     source ||= File.read(path)
    #     if defined?(RubyVM::InstructionSequence)
    #       RubyVM::InstructionSequence.compile(source)
    #     elsif defined?(JRUBY_VERSION)
    #       JRuby.compile(source)
    #     end
    #   end
    #
    # source://require-hooks//lib/require-hooks/api.rb#135
    def hijack_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # Returns the value of attribute print_warnings.
    #
    # source://require-hooks//lib/require-hooks/api.rb#93
    def print_warnings; end

    # Sets the attribute print_warnings
    #
    # @param value the value to set the attribute print_warnings to.
    #
    # source://require-hooks//lib/require-hooks/api.rb#93
    def print_warnings=(_arg0); end

    # Hack to enable coverage for hooked files.
    # Requires eval coverage to be on.
    # See https://bugs.ruby-lang.org/issues/22018 (https://github.com/ruby/ruby/pull/16805)
    #
    # source://require-hooks//lib/require-hooks/api.rb#160
    def setup_path_coverage(path, contents = T.unsafe(nil)); end

    # Define hooks to perform source-to-source transformations.
    # The return value MUST be either String (new source code) or nil (indicating that no transformations were performed).
    #
    # NOTE: The second argument (`source`) MAY be nil, indicating that no transformer tried to transform the source code.
    #
    #
    #    RequireHooks.source_transform do |path, source|
    #    end
    #
    # source://require-hooks//lib/require-hooks/api.rb#117
    def source_transform(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    private

    # @return [Boolean]
    #
    # source://require-hooks//lib/require-hooks/api.rb#184
    def eval_coverage_enabled?; end

    # source://require-hooks//lib/require-hooks/api.rb#174
    def register_hook(type, block, patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil)); end
  end
end

# source://require-hooks//lib/require-hooks/api.rb#4
class RequireHooks::Context
  # @return [Context] a new instance of Context
  #
  # source://require-hooks//lib/require-hooks/api.rb#8
  def initialize(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil)); end

  # Returns the value of attribute around_load.
  #
  # source://require-hooks//lib/require-hooks/api.rb#5
  def around_load; end

  # @return [Boolean]
  #
  # source://require-hooks//lib/require-hooks/api.rb#30
  def empty?; end

  # Returns the value of attribute exclude_patterns.
  #
  # source://require-hooks//lib/require-hooks/api.rb#5
  def exclude_patterns; end

  # @return [Boolean]
  #
  # source://require-hooks//lib/require-hooks/api.rb#45
  def hijack?; end

  # Returns the value of attribute hijack_load.
  #
  # source://require-hooks//lib/require-hooks/api.rb#5
  def hijack_load; end

  # @return [Boolean]
  #
  # source://require-hooks//lib/require-hooks/api.rb#24
  def match?(path); end

  # source://require-hooks//lib/require-hooks/api.rb#81
  def merge!(another_ctx); end

  # Returns the value of attribute patterns.
  #
  # source://require-hooks//lib/require-hooks/api.rb#5
  def patterns; end

  # source://require-hooks//lib/require-hooks/api.rb#59
  def perform_source_transform(path); end

  # @return [Boolean]
  #
  # source://require-hooks//lib/require-hooks/api.rb#35
  def readonly?; end

  # source://require-hooks//lib/require-hooks/api.rb#49
  def run_around_load_callbacks(path); end

  # Returns the value of attribute source_transform.
  #
  # source://require-hooks//lib/require-hooks/api.rb#5
  def source_transform; end

  # @return [Boolean]
  #
  # source://require-hooks//lib/require-hooks/api.rb#41
  def source_transform?; end

  # source://require-hooks//lib/require-hooks/api.rb#20
  def to_key; end

  # source://require-hooks//lib/require-hooks/api.rb#71
  def try_hijack_load(path, source); end
end

# source://require-hooks//lib/require-hooks/mode/load_iseq.rb#6
RequireHooks::EMPTY_ISEQ = T.let(T.unsafe(nil), RubyVM::InstructionSequence)

# source://require-hooks//lib/require-hooks/iseq.rb#4
module RequireHooks::Iseq
  class << self
    # source://require-hooks//lib/require-hooks/iseq.rb#6
    def compile_with_coverage(ctx, path); end
  end
end

# source://require-hooks//lib/require-hooks/mode/load_iseq.rb#8
module RequireHooks::LoadIseq
  # source://require-hooks//lib/require-hooks/mode/load_iseq.rb#9
  def load_iseq(path); end
end

class RubyVM::InstructionSequence
  extend ::RequireHooks::LoadIseq
end
