plugins:
  - rubocop-sorbet

AllCops:
  # We'll enable them as needed.
  # Don't want to accept any new ones without reviewing them.
  NewCops: disable
  Exclude:
    - "pkg/**/*"
    - "sorbet/**/*.rbi"
    - "tmp/**/*"
    - "vendor/**/*"

# Disable for RBS in comments.
Layout/LeadingCommentSpace:
  Enabled: false

# Need to allow long lines for RBS in comments because it doesn't support line breaks yet.
Layout/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 21

Metrics/PerceivedComplexity:
  Max: 11

Sorbet/EnforceSignatures:
  Enabled: true
  Style: "rbs"
  Exclude:
    - "**/*.rbi"
    - lib/optify_ruby/options_metadata.rb
    - test/**/*.rb

# Ensure all new files RBS.
Sorbet/ForbidSig:
  Enabled: true
  Exclude:
    - "**/*.rbi"
    - lib/optify_ruby/options_metadata.rb
    - test/**/*.rb

Sorbet/ForbidTAbsurd:
  Enabled: true

Sorbet/ForbidTBind:
  Enabled: true

Sorbet/ForbidTCast:
  Enabled: true

Sorbet/ForbidTLet:
  Enabled: true
  Exclude:
    - "**/*.rbi"

Sorbet/ForbidTMust:
  Enabled: true

Sorbet/ForbidTTypeAlias:
  Enabled: true

Sorbet/ForbidTUnsafe:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
