# frozen_string_literal: true
# typed: false

require "rake/testtask"
require "rake/extensiontask"
# require "rb_sys/toolchain_info"

task default: :test

# TODO See https://github.com/oxidize-rb/rb-sys/blob/main/gem/README.md for cross-compilation.
Rake::ExtensionTask.new("optify_ruby") do |ext|
  ext.lib_dir = "lib/optify_ruby"
  ext.source_pattern = "*.{rs,toml,lock,rb}"
  if ENV['RB_SYS_CROSS_COMPILE'] == 'true'
    # FIXME Get cross-compilation working.
    # See https://github.com/oxidize-rb/actions/blob/main/cross-gem/readme.md
    # Add more as needed.
    ext.cross_compile = true
    ext.cross_platform = [
      "arm64-darwin",
      "x86_64-darwin",
      "x86_64-linux",
    ]
  end
  ext.config_script = "extconf.rb"
end

task :dev do
  puts "Setting RB_SYS_CARGO_PROFILE to dev."
  ENV['RB_SYS_CARGO_PROFILE'] = 'dev'
end

Rake::TestTask.new do |t|
  if ENV['RB_SYS_CARGO_PROFILE'].nil?
    t.deps << :dev
  else
    puts "RB_SYS_CARGO_PROFILE: #{ENV['RB_SYS_CARGO_PROFILE']}"
  end
  t.deps << :compile
  t.test_files = FileList[File.expand_path("test/*_test.rb", __dir__)]
end
