# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `json5` gem.
# Please instead update this file by running `bin/tapioca gem json5`.

module JSON5
  def self.parse(source, opts = {}); end
end
