# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `liquid` gem.
# Please instead update this file by running `bin/tapioca gem liquid`.

module Liquid
  class Template
    def parse(source); end
    def render(context = {}); end
  end
end
