# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `listen` gem.
# Please instead update this file by running `bin/tapioca gem listen`.

module Listen
  class Listener
    def start; end
    def stop; end
  end

  def self.to(*directories, &block); end
end
