# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `optify-from_hash` gem.
# Please instead update this file by running `bin/tapioca gem optify-from_hash`.


# frozen_string_literal: true
# typed: strong

# source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#7
# Tools for working with configurations declared in files.
module Optify; end

# A base class for classes that can be created from a hash.
#
# @abstract It cannot be directly instantiated. Subclasses must implement the `abstract` methods below.
#
# source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#9
class Optify::FromHashable
  extend T::Sig
  extend T::Helpers

  abstract!

  # Compare this object with another object for equality.
  #
  # source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#108
  # Compare this object with another object for equality.
  # @param other The object to compare.
  # @return [Boolean] true if the objects are equal; otherwise, false.
  sig { params(other: T.untyped).returns(T::Boolean) }
  def ==(other); end

  # Convert this object to a Hash recursively.
  # This is mostly the reverse operation of `from_hash`,
  # as keys will be symbols
  # and `from_hash` will convert strings to symbols if that's how the attribute is declared.
  #
  # source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#123
  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def to_h; end

  private

  # source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#139
  sig { params(value: T.untyped).returns(T.untyped) }
  def _convert_value_to_hash(value); end

  class << self
    # Create a new immutable instance of the class from a hash.
    #
    # This is a class method so that it can set members with private setters.
    #
    # source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#20
    # Create a new instance of the class from a hash.
    # This is a class method that so that it can set members with private setters.
    # @param hash The hash to create the instance from.
    # @return The new instance.
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T.attached_class) }
    def from_hash(hash); end

    private

    # @raise [TypeError]
    #
    # source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#79
    sig { params(hash: T::Hash[T.untyped, T.untyped], type: T.untyped).returns(T.untyped) }
    def _convert_hash(hash, type); end

    # source://optify-from_hash//lib/optify_from_hash/from_hashable.rb#43
    sig { params(value: T.untyped, type: T.untyped).returns(T.untyped) }
    def _convert_value(value, type); end
  end
end
