# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rb_json5` gem.
# Please instead update this file by running `bin/tapioca gem rb_json5`.


# [JSON5](https://json5.org/) parser for Ruby
#
# source://rb_json5//lib/rb_json5/version.rb#3
module RbJSON5
  class << self
    # Reads a JSON5 string from the given file and parses it into its Ruby data structure
    #
    # @param filename [String] name of the given file
    # @param symbolize_names [Boolean] If set to true, converts names (keys) in a JSON5 object into Symbol
    # @return [Object] Ruby data structure represented by the input
    # @see RbJSON5.parse
    #
    # source://rb_json5//lib/rb_json5.rb#43
    def load_file(filename, symbolize_names: T.unsafe(nil)); end

    # Parses a JSON5 string into its Ruby data structure
    #
    # @param string_or_io [String, #read] JSON5 string itself or object like IO containing JSON5 string
    # @param symbolize_names [Boolean] If set to true, converts names (keys) in a JSON5 object into Symbol
    # @return [Object] Ruby data structure represented by the input
    # @see RbJSON5.load_file
    #
    # source://rb_json5//lib/rb_json5.rb#29
    def parse(string_or_io, symbolize_names: T.unsafe(nil)); end
  end
end

# Utility class to unescape the given escape sequence
#
# @api private
#
# source://rb_json5//lib/rb_json5/escape_sequence.rb#6
class RbJSON5::EscapeSequence
  # @api private
  # @param sequence [Parslet::Slice] escape sequence
  # @param valid_patterns [Array<Regexp>] list of patterns for valid unescaped character
  # @return [EscapeSequence] a new instance of EscapeSequence
  # @yield [character, sequence] call back block called when unespaced character is not matched
  #   with the given valid_patterns
  # @yieldparam character [String] character unescaped from the given escape sequence
  # @yieldparam sequence [Parslet::Slice] the given escape sequence
  #
  # source://rb_json5//lib/rb_json5/escape_sequence.rb#18
  def initialize(sequence, valid_patterns = T.unsafe(nil), &ifinvalid); end

  # returns the character unescaped from the given escape sequence
  #
  # @api private
  # @return [String] unescaped character
  #
  # source://rb_json5//lib/rb_json5/escape_sequence.rb#27
  def to_s; end

  private

  # @api private
  #
  # source://rb_json5//lib/rb_json5/escape_sequence.rb#40
  def unescape(sequence); end

  # @api private
  # @return [Boolean]
  #
  # source://rb_json5//lib/rb_json5/escape_sequence.rb#53
  def valid_character?(character, valid_patterns); end

  # @api private
  #
  # source://rb_json5//lib/rb_json5/escape_sequence.rb#48
  def validate(character, sequence, valid_patterns, ifinvalid); end
end

# list of charactors needing escape
#
# @api private
#
# source://rb_json5//lib/rb_json5/escape_sequence.rb#34
RbJSON5::EscapeSequence::ESCAPE_CHARACTERS = T.let(T.unsafe(nil), Hash)

# Exception class raised when the parse failed to match
#
# source://rb_json5//lib/rb_json5/parse_error.rb#5
class RbJSON5::ParseError < ::Parslet::ParseFailed; end

# JSON5 parser implementation using [Parslet](https://github.com/kschiess/parslet)
#
# Parsing process:
# 1. parses a JSON5 string into the intermediate structure
#    by using Parser.parser
# 2. convert the intermediate structure into Ruby objects
#    by using Parser.transform
#
# @api private
#
# source://rb_json5//lib/rb_json5/parser.rb#12
class RbJSON5::Parser
  extend ::Parslet

  # @api private
  # @param root [Symbol] specifies the root rule of the Parser for testing parpose
  # @return [Parser] a new instance of Parser
  #
  # source://rb_json5//lib/rb_json5/parser.rb#46
  def initialize(root = T.unsafe(nil)); end

  # parses a JSON5 string into the Ruby
  #
  # @api private
  # @param string_or_io [String, #read] JSON5 string itself or object like IO containing JSON5 string
  # @param symbolize_names [Boolean] If set to true, converts names (keys) in a JSON5 object into Symbol
  # @return [Object] Ruby data structure represented by the input
  # @see RbJSON5.parse
  # @see RbJSON5.load_file
  #
  # source://rb_json5//lib/rb_json5/parser.rb#57
  def parse(string_or_io, symbolize_names = T.unsafe(nil)); end

  private

  # @api private
  #
  # source://rb_json5//lib/rb_json5/parser.rb#76
  def error_reporter; end

  # @api private
  #
  # source://rb_json5//lib/rb_json5/parser.rb#66
  def parser; end

  # @api private
  #
  # source://rb_json5//lib/rb_json5/parser.rb#71
  def read_json5(string_or_io); end

  # @api private
  #
  # source://rb_json5//lib/rb_json5/parser.rb#80
  def transform; end

  class << self
    # returns the class to parse a JSON5 string
    #
    # @api private
    #
    # source://rb_json5//lib/rb_json5/parser.rb#17
    def parser; end

    # returns the class to convert the intermediate structure into Ruby objects
    #
    # @api private
    #
    # source://rb_json5//lib/rb_json5/parser.rb#22
    def transform; end

    private

    # defines a helper method within Parser.parser
    #
    # @api private
    #
    # source://rb_json5//lib/rb_json5/parser.rb#34
    def parse_helper(helper_name, &body); end

    # defines a rule how to parse the given JSON5 string
    #
    # @api private
    #
    # source://rb_json5//lib/rb_json5/parser.rb#29
    def parse_rule(rule_name, &body); end

    # defines a rule hot to convert tht intermediate strucure into Ruby objects
    #
    # @api private
    #
    # source://rb_json5//lib/rb_json5/parser.rb#39
    def transform_rule(expression, &body); end
  end
end

# list of patterns for part character of identifier
#
# source://rb_json5//lib/rb_json5/parser/object.rb#11
RbJSON5::Parser::IDENTIFIER_PART_PATTERNS = T.let(T.unsafe(nil), Array)

# list of patterns for start character of identifier
#
# source://rb_json5//lib/rb_json5/parser/object.rb#6
RbJSON5::Parser::IDENTIFIER_START_PATTERNS = T.let(T.unsafe(nil), Array)

# call back block called when character unescaped from Unicode escape sequence
# is not allowed for identifier
#
# source://rb_json5//lib/rb_json5/parser/object.rb#70
RbJSON5::Parser::INVALID_CHARACTER_FOR_IDENTIFIER = T.let(T.unsafe(nil), Proc)

# structure to keep a name/value pair for JSON5Object
#
# @api private
#
# source://rb_json5//lib/rb_json5/parser/object.rb#92
class RbJSON5::Parser::ObjectMember < ::Struct
  # Returns the value of attribute name
  #
  # @return [Object] the current value of name
  #
  # source://rb_json5//lib/rb_json5/parser/object.rb#92
  def name; end

  # Sets the attribute name
  #
  # @param value [Object] the value to set the attribute name to.
  # @return [Object] the newly set value
  #
  # source://rb_json5//lib/rb_json5/parser/object.rb#92
  def name=(_); end

  # Returns the value of attribute value
  #
  # @return [Object] the current value of value
  #
  # source://rb_json5//lib/rb_json5/parser/object.rb#92
  def value; end

  # Sets the attribute value
  #
  # @param value [Object] the value to set the attribute value to.
  # @return [Object] the newly set value
  #
  # source://rb_json5//lib/rb_json5/parser/object.rb#92
  def value=(_); end

  class << self
    # source://rb_json5//lib/rb_json5/parser/object.rb#92
    def [](*_arg0); end

    # source://rb_json5//lib/rb_json5/parser/object.rb#92
    def inspect; end

    # source://rb_json5//lib/rb_json5/parser/object.rb#92
    def keyword_init?; end

    # source://rb_json5//lib/rb_json5/parser/object.rb#92
    def members; end

    # source://rb_json5//lib/rb_json5/parser/object.rb#92
    def new(*_arg0); end
  end
end

# list of character codes of white space
#
# source://rb_json5//lib/rb_json5/parser/space.rb#17
RbJSON5::Parser::WHITE_SPACE_CODES = T.let(T.unsafe(nil), Array)

# Current version of RbJSON5
#
# source://rb_json5//lib/rb_json5/version.rb#5
RbJSON5::VERSION = T.let(T.unsafe(nil), String)
