# frozen_string_literal: true
# typed: false

require 'bundler/gem_tasks'
require 'rubocop/rake_task'
require 'rake/testtask'

# Customize the git tag format for releases
Bundler::GemHelper.instance.tap do |helper|
  helper.instance_eval do
    def tag_version
      "ruby-from_hash-v#{version}"
    end
  end
end

RuboCop::RakeTask.new

desc 'Run tests'
task default: :test

Rake::TestTask.new do |t|
  t.test_files = FileList[File.expand_path('test/*_test.rb', __dir__)]
end
