gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # Missing on MacOS
  # Maybe not needed to exclude since it's in the Gemfile.lock?
  # - rubydex
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
