# Tools for working with configurations declared in files.
module Optify
end

# A base class for classes that can be created from a hash.
class Optify::FromHashable
  # Create a new instance of the class from a hash.
  #
  # This is a class method that so that it can set members with private setters.
  # @param hash The hash to create the instance from.
  # @return The new instance.
  def self.from_hash: (::Hash[untyped, untyped] hash) -> instance

  # Convert this object to a Hash recursively.
  # This is mostly the reverse operation of `from_hash`,
  # as keys will be symbols
  # and `from_hash` will convert strings to symbols if that's how the attribute is declared.
  # @return The hash representation of this object.
  def to_h: () -> ::Hash[Symbol, untyped]

  # Compare this object with another object for equality.
  # @param other The object to compare.
  # @return [Boolean] true if the objects are equal; otherwise, false.
  def ==: (untyped other) -> bool
end
