AllCops:
  # We'll enable them as needed.
  # Don't want to accept any new ones without reviewing them.
  NewCops: disable

# Disable for RBS in comments.
Layout/LeadingCommentSpace:
  Enabled: false

# Need to allow long lines for RBS in comments because it doesn't support line breaks yet.
Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 22

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 21

Metrics/PerceivedComplexity:
  Max: 10
