name: "Build"

on:
  push:
    branches: [ "main" ]
    paths:
      - "rust/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "rust/**"
      - "tests/**"


  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "[Rust] [optify] Build"
      run: cargo build --release
      working-directory: ./rust/optify
    - name: "[Rust] [optify] Lint"
      run : cargo fmt -- --check
      working-directory: ./rust/optify
    - name: "[Rust] [optify] Clippy"
      run: cargo clippy --release -- -D warnings
      working-directory: ./rust/optify
    - name: "[Rust] [optify] Test"
      run: cargo test --release
      working-directory: ./rust/optify
