name: "Cross-Build"

on:
  push:
    branches: [ "main" ]
    paths:
      - "ruby/**"
      - "rust/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ruby/**"
      - "rust/**"
      - "tests/**"

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RB_SYS_CARGO_PROFILE: release

jobs:
  test:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_platform:
        # TODO Add once we confirm it works as needed.
        # More versions in https://raw.githubusercontent.com/oxidize-rb/rb-sys/main/data/derived/github-actions-matrix.json
        - x86_64-linux
        # - x86_64-darwin
        - arm64-darwin
        ruby_version:
        - "3.3"
    steps:
    - uses: actions/checkout@v4

    - name: "Remove .ruby-version"
      shell: bash
      run: |
        rm ruby/optify/.ruby-version

    # - uses: oxidize-rb/actions/setup-ruby-and-rust@main
    #   with:
    #     ruby-version: ${{ matrix.ruby_version }}
    #     bundler-cache: true
    #     cargo-cache: true
    #     cache-save-always: false
    #     cargo-vendor: true
    #     cache-version: v0-${{ matrix.ruby_platform }}
    #     working-directory: ./rust/optify
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby_version }}

    - name: "Versions"
      shell: bash
      run: |
        ruby --version
        rustup --version

    - name: "[Rust] Build"
      run: cargo build --release
      working-directory: ./rust/optify

    - uses: oxidize-rb/actions/cross-gem@main
      id: cross-gem
      with:
        cache-save-always: false
        platform: ${{ matrix.ruby_platform }}
        ruby-versions: "3.3"
        # Available versions: https://cache.ruby-lang.org/pub/misc/ci_versions/cruby.json
        # Found in https://github.com/oxidize-rb/actions/blob/main/fetch-ci-data/evaluate.rb
        # When we're ready:
        # ruby-versions: "3.3,3.4"
        working-directory: ./ruby/optify
