name: "Test"

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/test.yml"
      - "ruby/**"
      - "rust/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/test.yml"
      - "ruby/**"
      - "rust/**"
      - "tests/**"

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RB_SYS_CARGO_PROFILE: release
  RB_SYS_CROSS_COMPILE: true

jobs:
  test:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v4

    # Rust
    - name: "[Rust] [optify] Build"
      run: cargo build --release
      working-directory: ./rust/optify
    - name: "[Rust] [optify] Lint"
      run : cargo fmt -- --check
      working-directory: ./rust/optify
    - name: "[Rust] [optify] Clippy"
      run: cargo clippy --release -p optify --no-deps -- -D warnings --no-deps
      working-directory: ./rust/optify
    - name: "[Rust] [optify] Test"
      run: cargo test --release
      working-directory: ./rust/optify

    # Ruby
    # setup-ruby also runs `bundle install`.
    # It uses the Ruby version from .ruby-version.
    - uses: ruby/setup-ruby@v1
      name: "[Ruby] Setup"
      with:
        bundler-cache: true
        working-directory: ./ruby/optify
    - name: "[Ruby] Lint"
      run: |
        bundle exec srb tc
        bundle exec rubocop
      working-directory: ./ruby/optify
    - name: "[Ruby] Test"
      run: bundle exec rake test
      working-directory: ./ruby/optify
